blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/ArQ2puK
    about: Have questions or need support? Please go to the Discord server, as issues that are just support-related will be closed and redirected there.
